### PR TITLE
r/sakuracloud_switch: add `network_mask_len` and `default_route` attributes

### PR DESCRIPTION
**Pull request by kurochan**
Add `network_mask_len` and `default_route` attributes to resource `sakuracloud_switch` .

### CODE REVIEW

**Comment by yamamoto-febc** [comment]
Hi @kurochan, thank you for opening the PR.

What is the use case for this PR?

The handling of the network_mask_len and default_route attributes of the switch is a bit tricky and detailed behavior is not documented in [the API document](https://developer.sakura.ad.jp/cloud/api/1.1/switch/), so we do not want to support use cases that depend on their behavior.

**Comment by kurochan** [comment]
@yamamoto-febc This is because we want to get the value as Metadata for cloud-init.
https://manual.sakura.ad.jp/cloud/server/cloud-init.html
Metadata `Server.Interfaces[].UserIPAddress` gives the only IP address, but not the subnet mask.
If I can set `NetworkMaskLen` by terraform, I can use template variable `{{ ds.meta_data.Server.Interfaces[1].UserIPAddress }}/{{ ds.meta_data.Server.Interfaces[1].Switch. UserSubnet.NetworkMaskLen }}` by cloud-init.

`DefaultRoute` is not planned to be used.

**Comment by yamamoto-febc** [comment]
@kurochan Sorry for the delay and thanks for sharing your use case.

I think your use case is reasonable and practical one.
However, as mentioned above, we do not want to support use cases that depend on the behavior of Switch's API.
It may cause unexpected problems.

One tricky example of the switch API is that if a new server is connected after the switch's UserSubnet is set, the UserSubnet is overwritten.

I think it would be better to take a different approach, such as managing NetworkMaskLen at the tf file layer.

**Comment by kurochan** [comment]
I understand, thanks for explaining!

**Pull request closed without merging**
